{
 "title": "VMWare",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host: ",
    "query": {
     "query": "label_values(vmware_host_processor_speed{job=\"vmware-exporter\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM Memory Active",
     "type": "stat",
     "description": "Quantidade de memória a VM está ativamente utilizando",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_vm_memory_active{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "VM Memory Mapped",
     "type": "stat",
     "description": "Quantidade de memória alocada para a VM. Exclui balloon, swap ou memória que nunca foi acessada",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_vm_memory_mapped{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "VM Memory Used on Host",
     "type": "stat",
     "description": "Estimativa da quantidade de memoria fisica no host está sendo consumida por essa vm",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_vm_memory_used{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "VM Memory Shared",
     "type": "stat",
     "description": "quantidade de memória física associada a esta máquina que é copy-on-write (COW) compartilhada no host",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_vm_memory_shared{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "VM Memory Reservation",
     "type": "stat",
     "description": "Quantidade de memória reservada para essa VM no host.",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_vm_memory_reservation{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "VM Memory Limit",
     "type": "stat",
     "description": "Limite máximo de memória que está disponível para essa VM",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_vm_memory_limit{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "VM Memory Target Size",
     "type": "stat",
     "description": "Quantidade de memória que se espera ter alocado para essa vm ",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_vm_memory_target_size{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "VM Memory Shared Saved",
     "type": "stat",
     "description": "quantidade estimada de memória física no host salva da memória física compartilhada do convidado de copy-on-write  (COW).",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_vm_memory_shared_saved{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "VM Memory Swapped",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_vm_memory_swapped{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "VM Ballooned",
     "type": "stat",
     "description": "Quantidade de memoria virtual que foi recuperada pelo driver de balloon (aka vmmemctl)",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_vm_ballooned{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "VM Memory Shares",
     "type": "stat",
     "description": "Número de memory shared alocados para essa vm",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_vm_memory_shares{instance=\"$node\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Used CPU",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_vm_processor_time{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "VM Speed in MHz",
     "type": "stat",
     "description": "Velocidade em MHz do processador da VM.",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_vm_processor_effective_speed{instance=\"$node\"}*1000000"
      }
     ]
    },
    {
     "title": "% Cpu Ready",
     "type": "gauge",
     "description": "Significa que a CPU está com x% esperando o host.\nConta utilizada:\nround((new_stolen_ms - old_stolen_ms) * 100.0 / (new_elapsed_ms - old_elapsed_ms), 2)",
     "gridPos": { "h": 6, "w": 5, "x": 10, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_vm_processor_stolen_time{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "VM Processor Limit",
     "type": "stat",
     "description": "Limite máximo do processador disponível para essa VM",
     "gridPos": { "h": 3, "w": 5, "x": 15, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_vm_processor_limit{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "CPU Shares",
     "type": "stat",
     "description": "Número de CPU shares alocato para a VM\nhttps://docs.vmware.com/en/VMware-vSphere/6.7/vsphere-esxi-vcenter-server-672-resource-management-guide.pdf, página 16",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_vm_processor_shares{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "VM Processor Reservation",
     "type": "stat",
     "description": "Reserva garantida de Mhz para essa VM",
     "gridPos": { "h": 3, "w": 5, "x": 15, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_vm_processor_reservation{instance=\"$node\"}*1000000"
      }
     ]
    },
    {
     "title": "Host Processor Speed in MHz",
     "type": "stat",
     "description": "Velocidade do processador do HOSPEDEIRO",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_host_processor_speed{instance=\"$node\"}*1000000"
      }
     ]
    }
   ]
  }
 ]
}